version: "3.8"

x-airflow-env: &airflow-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
  AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "30"
  AIRFLOW__CORE__DEFAULT_TIMEZONE: "America/Sao_Paulo"
  AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: "America/Sao_Paulo"
  AIRFLOW__WEBSERVER__SECRET_KEY: "desafio-engenhariadedados-indicium"
  AIRFLOW__CORE__FERNET_KEY: "hST3O9p0oF3j3rzkJuUWZ_6K12vIr2v-r_eL0urJEwA="

services:
  airflow-db:
    image: postgres:16
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: lucas_airflow
      POSTGRES_PASSWORD: wolfria
    ports:
      - "55433:5432"
    volumes:
      - ./airflow_dbdata:/var/lib/postgresql/data

  airflow-init:
    build: ./airflow
    entrypoint: ["/bin/bash", "-c"]
    environment:
      <<: *airflow-env
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://lucas_airflow:wolfria@airflow-db:5432/airflow
    depends_on:
      - airflow-db
    command: >
      bash -c "
      airflow db init &&
      airflow users create
        --username airflow_lucas
        --firstname Lucas
        --lastname Teixeira
        --role Admin
        --email lucas_airflow123@gmail.com
        --password wolfria123
      "

  airflow-webserver:
    build: ./airflow
    environment:
      <<: *airflow-env
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://lucas_airflow:wolfria@airflow-db:5432/airflow
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project
      - ./airflow/logs:/opt/airflow/logs
    command: webserver

  airflow-scheduler:
    build: ./airflow
    environment:
      <<: *airflow-env
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://lucas_airflow:wolfria@airflow-db:5432/airflow
    depends_on:
      - airflow-init
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project
      - ./airflow/logs:/opt/airflow/logs
    command: scheduler

